### ISSUE TITLE
Question about the performances of other models

### ISSUE THREAD

**Issue by heqin-zhu** [uci-cbcl/UFold#28]
Hi, 
Thanks for your excellent work. I have some questions about the performances in the paper:
1. How do you obtain the performances of other models? "Retrain and test" or "Test" or "Copy from original paper"?
2. The performance of E2Efold in your paper seems extremely bad. Could you make some explanations? 

Best wishes!

**Comment by sperfu** [comment]
Hi there,

Thank you for the questions. Firstly, we evaluate the performance of other models through "Retrain and test" (if the model provides a pretrained model, we use it for testing). Secondly, regarding the performance of e2efold, you can observe that its performance on the RNAStalign dataset is relatively consistent with their reported results. However, on other cross-validation datasets, it does not seem to perform as well, similar to the results reported in other papers such as MXFold2, etc.

Thanks.

**Comment by heqin-zhu** [comment]
Thanks for your fast reply！
